Repository NixOS/nixos-artwork, pull requests merged in 2024-04, with the labels that each got.

#121 README: updates
  README.md
Labels: 0. type cleanup, 2. topic: meta

#122 Matrix icons rollup 2024 04 08
  matrix/icons.src.svg
Labels: 0. type: contribution, 2. topic: matrix

#120 Make icons squared, and fix build
  .gitignore
  bootloader/Makefile
  default.nix
  icons/Makefile
  logo/nix-snowflake-colours.svg
  logo/nix-snowflake-white.svg
  logo/nix-snowflake.svg
  logo/white.png
  shell.nix
Labels: 0. type: defect

#117 Vacuum SVGs with Inkscape
  bootloader/efi-background.svg
  logo/nix-snowflake-colours.svg
  logo/nix-snowflake-white.svg
  logo/nix-social-preview.svg
  logo/nixos-social-preview.svg
  logo/nixos-text-below.svg
  logo/nixos-white.svg
  logo/nixos.svg
  logo/nixos.text.svg
  thumbnails/summer-of-nix-template.svg
  wallpapers/nix-wallpaper-nineish-dark-gray.svg
  wallpapers/nix-wallpaper-nineish-solarized-dark.src.svg
  wallpapers/nix-wallpaper-nineish-solarized-light.src.svg
  wallpapers/nix-wallpaper-nineish.src.svg
  weekly/nixos-weekly.svg
Labels: 0. type cleanup

#124 social preview: Move into a `social` directory
  logo/nix-social-preview.png
  logo/nixos-social-preview.png
  social/README.md
  social/nix-social-preview.svg
  social/nixos-social-preview.svg
  social/summer-of-nix-thumbnail-template.svg
Labels: 0. type cleanup, 2. topic: official

#127 Mainly removes old logo sightings
  CONTRIBUTORS.md
  common/grub2-background/grub-nixos-1.png
  common/grub2-background/grub-nixos-1.xcf
  common/grub2-background/grub-nixos-2.png
  common/grub2-background/grub-nixos-2.xcf
  common/grub2-background/grub-nixos-3.png
  common/grub2-background/grub-nixos-3.xcf
  common/wallpapers/nixos-border.png
  gnome/default.nix
  gnome/share/gnome-background-properties/template.xml.in
  grub-background/grub-1.xpm
  kde/share/wallpapers/nixos-stripes/nixos-stripes.png
  kde/share/wallpapers/nixos-stripes/nixos-stripes.png.desktop
  kde/share/wallpapers/nixos-stripes/nixos-stripes.xcf
  slim/themes/nixos-theme.tar.gz
  swag/flyers/happier-hacking/Readme.md
  swag/flyers/happier-hacking/flyer-multi.pdf
  swag/flyers/happier-hacking/flyer-optimized.svg
  weekly/README.md
  weekly/nixos-weekly.svg
Labels: 0. type cleanup, 2. topic: official

#123 logo: Provide an easy path to optimized SVGs and exported PNGs
  default.nix
  logo/README.md
  logo/default.nix
  logo/package.nix
Labels: 0. type cleanup, 2. topic: official
